name: action_workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code_checkout
        uses: actions/checkout@v3
  
      - name: install_python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: run_script
        run: |
          python3.9 src/print_value.py
  
  print:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: print_var
        run: |
          echo "Variable: ${{ vars.username }}"
          echo "Secret: ${{ secrets.pwd }}"
