name: wrkflw
on: workflow_dispatch

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: list statement
        run: |
          cd src
          ls -lstr
          ./print_value.py
